# Building Stock Indices

Note: __yfinance can be unstable/unreliable from time to time__ when it comes to downloading fundamental data with the ticker object. In particular, __ticker.get_info()__ can be flawed.

__Action required__: Check for the __latest yfinance versions__ and update with the following command (Anaconda Prompt / Terminal):

pip install yfinance --upgrade

In the following, I have added an __alternative Yahoo Finance API Wrapper__, __yahooquery__

__Action required: Please install yahooquery with the following command (Anaconda Prompt / Terminal):__

pip install yahooquery --upgrade

Note: 
- Please make sure you have installed the __latest__ yahooquery version (if not, please upgrade).

__Update December 2023__: Sometimes yfinance is more stable/reliable and sometimes yahooquery is more stable/reliable. Most recently, yfinance seemed to be better. In any case, __please make sure you have the latest versions installed!__

## Getting started

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [2]:
df = pd.read_csv("DJI_Const.csv", header = [0, 1], index_col = 0, parse_dates=[0])
df

           Adj Close                                                         \
                AAPL   AMGN    AXP     BA    CAT    CRM  CSCO    CVX    DIS
Date
2020-08-31    127.29 238.22  98.72 171.82 135.37 272.65 39.41  76.45 131.87
2020-09-01    132.36 235.90  99.58 172.10 138.93 281.25 39.23  75.67 133.55
2020-09-02    129.62 242.73 101.45 174.78 141.99 276.69 39.59  75.77 135.39
2020-09-03    119.24 233.13 101.51 168.77 139.60 265.01 38.22  74.94 133.24
2020-09-04    119.32 233.59 102.69 171.05 140.95 254.70 38.10  74.63 131.99
...              ...    ...    ...    ...    ...    ...   ...    ...    ...
2022-11-09    134.87 289.65 145.86 168.74 225.54 142.06 43.91 177.93  86.75
2022-11-10    146.87 291.01 154.75 177.58 232.45 156.30 45.66 181.30  90.46
2022-11-11    149.70 285.02 154.89 177.49 236.49 157.73 44.79 186.46  95.01
2022-11-14    148.28 285.30 154.13 173.55 236.50 158.66 44.74 186.55  94.28
2022-11-15    150.04 283.60 153.89 175.35 234.59 162.07 44.90 188.05  95.51

                  ...    Volume                                       \
             DOW  ...      MSFT       NKE       PG      TRV      UNH
Date              ...
2020-08-31 41.15  ...  28774200   3519800  5596800  2297900  4341600
2020-09-01 43.11  ...  25725500   4912400  5671800   969900  2487100
2020-09-02 44.89  ...  34080800   6775400  8384800  1391400  2846500
2020-09-03 44.13  ...  58400300   7264400  7277900  1299400  3872500
2020-09-04 44.32  ...  59664100   5157600  7437700  1460700  2901000
...          ...  ...       ...       ...      ...      ...      ...
2022-11-09 47.68  ...  27852900   6550900  5690700   999200  2672600
2022-11-10 49.96  ...  46268000   9361000  8068700  1618000  3426400
2022-11-11 53.14  ...  34600900  12595600  7174400  1403300  7032900
2022-11-14 51.95  ...  31123300   7134900  8516200  1427300  5238400
2022-11-15 51.60  ...  31367300   7241000  7731700  1445900  5102800


                   V        VZ       WBA       WMT       ^DJI
Date
2020-08-31   9326900  14555500   7940100  15078800  517320000
2020-09-01   5642900  13358400  10728300  35599400  423410000
2020-09-02   9863800  21711900   7672400  17222000  539510000
2020-09-03  11310200  23126800   8278000  16005000  650080000
2020-09-04  13243600  22250100   6994400  11327400  694640000
...              ...       ...       ...       ...        ...
2022-11-09   7320200  17574600   6830500   5310700  355200000
2022-11-10   8048900  23049000   8825000   6770200  480130000
2022-11-11   9600700  22978900  13098600   6419700  427790000
2022-11-14   5796100  23028500   8301900  12508600  354340000
2022-11-15   7315700  25058900   6755300  25504700  390610000

[558 rows x 186 columns]

In [3]:
df.dropna(inplace = True)
df

           Adj Close                                                         \
                AAPL   AMGN    AXP     BA    CAT    CRM  CSCO    CVX    DIS
Date
2020-08-31    127.29 238.22  98.72 171.82 135.37 272.65 39.41  76.45 131.87
2020-09-01    132.36 235.90  99.58 172.10 138.93 281.25 39.23  75.67 133.55
2020-09-02    129.62 242.73 101.45 174.78 141.99 276.69 39.59  75.77 135.39
2020-09-03    119.24 233.13 101.51 168.77 139.60 265.01 38.22  74.94 133.24
2020-09-04    119.32 233.59 102.69 171.05 140.95 254.70 38.10  74.63 131.99
...              ...    ...    ...    ...    ...    ...   ...    ...    ...
2022-11-09    134.87 289.65 145.86 168.74 225.54 142.06 43.91 177.93  86.75
2022-11-10    146.87 291.01 154.75 177.58 232.45 156.30 45.66 181.30  90.46
2022-11-11    149.70 285.02 154.89 177.49 236.49 157.73 44.79 186.46  95.01
2022-11-14    148.28 285.30 154.13 173.55 236.50 158.66 44.74 186.55  94.28
2022-11-15    150.04 283.60 153.89 175.35 234.59 162.07 44.90 188.05  95.51

                  ...    Volume                                       \
             DOW  ...      MSFT       NKE       PG      TRV      UNH
Date              ...
2020-08-31 41.15  ...  28774200   3519800  5596800  2297900  4341600
2020-09-01 43.11  ...  25725500   4912400  5671800   969900  2487100
2020-09-02 44.89  ...  34080800   6775400  8384800  1391400  2846500
2020-09-03 44.13  ...  58400300   7264400  7277900  1299400  3872500
2020-09-04 44.32  ...  59664100   5157600  7437700  1460700  2901000
...          ...  ...       ...       ...      ...      ...      ...
2022-11-09 47.68  ...  27852900   6550900  5690700   999200  2672600
2022-11-10 49.96  ...  46268000   9361000  8068700  1618000  3426400
2022-11-11 53.14  ...  34600900  12595600  7174400  1403300  7032900
2022-11-14 51.95  ...  31123300   7134900  8516200  1427300  5238400
2022-11-15 51.60  ...  31367300   7241000  7731700  1445900  5102800


                   V        VZ       WBA       WMT       ^DJI
Date
2020-08-31   9326900  14555500   7940100  15078800  517320000
2020-09-01   5642900  13358400  10728300  35599400  423410000
2020-09-02   9863800  21711900   7672400  17222000  539510000
2020-09-03  11310200  23126800   8278000  16005000  650080000
2020-09-04  13243600  22250100   6994400  11327400  694640000
...              ...       ...       ...       ...        ...
2022-11-09   7320200  17574600   6830500   5310700  355200000
2022-11-10   8048900  23049000   8825000   6770200  480130000
2022-11-11   9600700  22978900  13098600   6419700  427790000
2022-11-14   5796100  23028500   8301900  12508600  354340000
2022-11-15   7315700  25058900   6755300  25504700  390610000

[558 rows x 186 columns]

In [4]:
close = df.Close.copy()
close

,AAPL,AMGN,AXP,BA,CAT,CRM,CSCO,CVX,DIS,DOW,...,MSFT,NKE,PG,TRV,UNH,V,VZ,WBA,WMT,^DJI
Date,,,,,,,,,,,,,,,,,,,,,
2020-08-31,129.04,253.32,101.59,171.82,142.31,272.65,42.22,83.93,131.87,45.12,...,225.53,111.89,138.33,116.04,312.55,211.99,59.27,38.02,138.85,28430.05
2020-09-01,134.18,250.86,102.47,172.10,146.05,281.25,42.03,83.08,133.55,47.27,...,227.27,114.84,138.18,114.69,312.83,213.35,59.16,36.76,147.59,28645.66
2020-09-02,131.40,258.12,104.40,174.78,149.27,276.69,42.42,83.19,135.39,49.22,...,231.65,116.80,140.51,117.48,320.24,216.48,60.53,37.17,147.68,29100.50
2020-09-03,120.88,247.91,104.46,168.77,146.76,265.01,40.95,82.28,133.24,48.39,...,217.30,112.85,138.26,115.35,316.23,208.96,60.61,37.09,144.54,28292.73
2020-09-04,120.96,248.40,105.67,171.05,148.18,254.70,40.82,81.93,131.99,48.60,...,214.25,112.40,137.96,116.57,312.00,204.66,60.48,36.89,142.83,28133.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-11-09,134.87,289.65,145.86,168.74,225.54,142.06,43.91,177.93,86.75,47.68,...,224.51,92.10,136.48,182.15,540.66,193.93,37.62,36.89,139.47,32513.94
2022-11-10,146.87,291.01,154.75,177.58,232.45,156.30,45.66,181.30,90.46,49.96,...,242.98,99.49,141.18,183.30,544.17,205.57,38.52,38.49,142.36,33715.37
2022-11-11,149.70,285.02,154.89,177.49,236.49,157.73,44.79,186.46,95.01,53.14,...,247.11,106.09,140.97,181.73,522.08,205.00,38.30,41.26,142.58,33747.86
2022-11-14,148.28,285.30,154.13,173.55,236.50,158.66,44.74,186.55,94.28,51.95,...,241.55,104.39,140.98,182.70,513.75,206.86,38.31,40.54,138.39,33536.70
2022-11-15,150.04,283.60,153.89,175.35,234.59,162.07,44.90,188.05,95.51,51.60,...,241.97,106.71,140.49,179.50,503.01,209.99,37.70,40.65,147.44,33592.92

In [5]:
returns = close.pct_change() # simple returns
returns

,AAPL,AMGN,AXP,BA,CAT,CRM,CSCO,CVX,DIS,DOW,...,MSFT,NKE,PG,TRV,UNH,V,VZ,WBA,WMT,^DJI
Date,,,,,,,,,,,,,,,,,,,,,
2020-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-01,0.04,-0.01,0.01,0.00,0.03,0.03,-0.00,-0.01,0.01,0.05,...,0.01,0.03,-0.00,-0.01,0.00,0.01,-0.00,-0.03,0.06,0.01
2020-09-02,-0.02,0.03,0.02,0.02,0.02,-0.02,0.01,0.00,0.01,0.04,...,0.02,0.02,0.02,0.02,0.02,0.01,0.02,0.01,0.00,0.02
2020-09-03,-0.08,-0.04,0.00,-0.03,-0.02,-0.04,-0.03,-0.01,-0.02,-0.02,...,-0.06,-0.03,-0.02,-0.02,-0.01,-0.03,0.00,-0.00,-0.02,-0.03
2020-09-04,0.00,0.00,0.01,0.01,0.01,-0.04,-0.00,-0.00,-0.01,0.00,...,-0.01,-0.00,-0.00,0.01,-0.01,-0.02,-0.00,-0.01,-0.01,-0.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-11-09,-0.03,-0.01,-0.03,-0.01,-0.02,-0.03,-0.02,-0.04,-0.13,-0.04,...,-0.02,-0.02,-0.00,-0.01,-0.02,-0.04,-0.01,-0.04,-0.02,-0.02
2022-11-10,0.09,0.00,0.06,0.05,0.03,0.10,0.04,0.02,0.04,0.05,...,0.08,0.08,0.03,0.01,0.01,0.06,0.02,0.04,0.02,0.04
2022-11-11,0.02,-0.02,0.00,-0.00,0.02,0.01,-0.02,0.03,0.05,0.06,...,0.02,0.07,-0.00,-0.01,-0.04,-0.00,-0.01,0.07,0.00,0.00
2022-11-14,-0.01,0.00,-0.00,-0.02,0.00,0.01,-0.00,0.00,-0.01,-0.02,...,-0.02,-0.02,0.00,0.01,-0.02,0.01,0.00,-0.02,-0.03,-0.01
2022-11-15,0.01,-0.01,-0.00,0.01,-0.01,0.02,0.00,0.01,0.01,-0.01,...,0.00,0.02,-0.00,-0.02,-0.02,0.02,-0.02,0.00,0.07,0.00

In [6]:
index = "^DJI"

In [ ]:
const = close.columns.drop([index])
const

## Building a Price-weighted Index

In [ ]:
close[const]

In [ ]:
close[const].sum(axis = 1).iloc[0] # sum of prices day 1

__Index (Base Value = 100)__

In [ ]:
pwi = close[const].sum(axis = 1).div(close[const].sum(axis = 1).iloc[0]).mul(100)
pwi

In [ ]:
pwi.name = "pwi"
pwi

__Cross-Check with DJI Data__

In [ ]:
dji_norm = close["^DJI"].div(close["^DJI"].iloc[0]).mul(100)
dji_norm

In [ ]:
pwi.plot(figsize = (12, 8))
dji_norm.plot()
plt.legend()
plt.show()

__Weights over time__

In [ ]:
weights_PWI = close[const].div(close[const].sum(axis = 1), axis = "rows")
weights_PWI

In [ ]:
weights_PWI.plot(figsize = (15, 8), fontsize = 13)
plt.title("PWI - Weights", fontsize = 15)
plt.legend(fontsize = 13)
plt.show()

In [ ]:
weights_PWI[["AAPL", "MSFT"]].plot(figsize = (15, 8), fontsize = 13)
plt.title("PWI - Weights", fontsize = 15)
plt.legend(fontsize = 13)
plt.show()

## Building an Equal-weighted Index

In [ ]:
returns

In [ ]:
mean_ret = returns[const].mean(axis = 1)
mean_ret

In [ ]:
ewi = mean_ret.add(1).cumprod().mul(100)
ewi

In [ ]:
ewi.iloc[0] = 100

In [ ]:
ewi.name = "ewi"
ewi

## Building a Value-weighted Index (Part 1)

__Historical Market Caps__

- Hard to get from free Web Soruces
- Still, we can calculate an approximation with yahoo finance data
- Course might cover a paid data source with historical market caps

In [ ]:
import yfinance as yf
from yahooquery import Ticker

In [ ]:
const

In [ ]:
ticker = yf.Ticker(ticker = "AAPL") #yfinance
ticker

In [ ]:
info = pd.Series(ticker.get_info()) # yfinance
info

In [ ]:
shares = info["sharesOutstanding"] #yfinance
shares

In [ ]:
shares = Ticker("AAPL").key_stats["AAPL"]["sharesOutstanding"] #yahooquery
shares

In [ ]:
mcap = close.AAPL * shares
mcap

(Simplified) Assumption: __Outstanding Shares remained constant__ in the most recent time period (no new share issues or buy-backs)

In [ ]:
mcap = close[const].copy() # dummy df to insert mcaps
mcap

In [ ]:
# yfinance (recommended)
count = 1
for symbol in const:
    try:
        shares = yf.Ticker(ticker = symbol).get_info()["sharesOutstanding"]
        mcap[symbol] = mcap[symbol] * shares
        print(count, end = '\r')
        count += 1
    except Exception as e:
        print("{} not found".format(symbol))
print("Download complete.")

In [ ]:
# yahooquery (slow)
count = 1
for symbol in const:
    try:
        shares = Ticker(symbols = symbol).key_stats[symbol]["sharesOutstanding"]
        mcap[symbol] = mcap[symbol] * shares
        print(count, end = '\r')
        count += 1
    except Exception as e:
        print("{} not found".format(symbol))
print("Download complete.")

In [ ]:
mcap.iloc[-1].sort_values(ascending = False)

In [ ]:
plt.figure(figsize = (12, 8))
mcap.iloc[-1].sort_values().plot.pie()
plt.show()

## Building a Value-weighted Index (Part 2)

In [ ]:
mcap

In [ ]:
total_mcap = mcap.sum(axis = "columns") # total market cap
total_mcap

In [ ]:
total_mcap.plot(figsize = (12, 8))
plt.title("Total Market Cap DJIA")
plt.show()

__Weights over time__

In [ ]:
weights_VWI = mcap.div(total_mcap, axis = "rows")
weights_VWI

In [ ]:
weights_VWI.sum(axis = "columns")

In [ ]:
weights_VWI.plot(figsize = (15, 8), fontsize = 13)
plt.title("PWI - Weights", fontsize = 15)
plt.legend(fontsize = 13)
plt.show()

In [ ]:
returns # daily return

In [ ]:
weights_VWI # weights at the end of the day

In [ ]:
mcwr = returns[const].mul(weights_VWI.shift()).sum(axis = "columns")
mcwr # simple returns vwi

In [ ]:
vwi = mcwr.add(1).cumprod().mul(100)
vwi

In [ ]:
vwi.name = "vwi"
vwi

## Analysis and Comparison (Part 1)

In [ ]:
indices = pd.concat([vwi, pwi, ewi], axis = 1).iloc[:-1]
indices

In [ ]:
indices.plot(figsize = (12, 8))
plt.title("VWI vs. PWI vs. EWI", fontsize = 15)
plt.show()

__Keep in mind:__ While VWI and PWI are (mostly) __self-rebalancing__, EWI requires/assumes __daily rebalancing__! -> __Trading Costs__!

## Analysis and Comparison (Part 2)

In [ ]:
indices

In [ ]:
close

In [ ]:
prices_m = pd.concat([close[const], indices], axis = 1)
prices_m

In [ ]:
returns_m = prices_m.pct_change().dropna() # simple returns
returns_m

In [ ]:
def ann_risk_return(returns_df): # assumes simple returns as input
    summary = pd.DataFrame(index = returns_df.columns)
    summary["ann. Risk"] = returns_df.std() * np.sqrt(252)
    log_returns = np.log(returns_df + 1)
    summary["CAGR"] = np.exp(log_returns.mean() * 252) - 1
    return summary

In [ ]:
summary = ann_risk_return(returns_m)
summary

In [ ]:
summary.plot(kind = "scatter", x = "ann. Risk", y = "CAGR", figsize = (15,12), s = 50, fontsize = 15)
for i in summary.index:
    plt.annotate(i, xy=(summary.loc[i, "ann. Risk"]+0.005, summary.loc[i, "CAGR"]+0.005), size = 10)
plt.grid()
plt.xlabel("ann. Risk (std)", fontsize = 15)
plt.ylabel("CAGR", fontsize = 15)
plt.title("Risk-Return Analysis", fontsize = 20)
plt.show()

- All three Indexes benefit from the __Portfolio Diversification Effect__!
- __Concentrated Positions__ negatively affect __VWI__
- PWI and EWI are closely together (before Trading Costs)
- But: EWI requires __daily rebalancing__! (Trading Costs)

## The DJIA Total Return Index

In [ ]:
weights_PWI # based on Close Prices

In [ ]:
total_returns = df["Adj Close"].pct_change() # Adj Close Prices!
total_returns

In [ ]:
returns_tr = total_returns[const].mul(weights_PWI.shift()).sum(axis = "columns")
returns_tr # simple returns DJI Total Return Index

In [ ]:
dji_tr = returns_tr.add(1).cumprod().mul(100)
dji_tr

In [ ]:
returns_m["DJI_TR"] = returns_tr
returns_m

In [ ]:
summary = ann_risk_return(returns_m)
summary

In [ ]:
summary.plot(kind = "scatter", x = "ann. Risk", y = "CAGR", figsize = (15,12), s = 50, fontsize = 15)
for i in summary.index:
    plt.annotate(i, xy=(summary.loc[i, "ann. Risk"]+0.005, summary.loc[i, "CAGR"]+0.005), size = 10)
plt.grid()
plt.xlabel("ann. Risk (std)", fontsize = 15)
plt.ylabel("CAGR", fontsize = 15)
plt.title("Risk-Return Analysis", fontsize = 20)
plt.show()